# Generated by Django 3.1.3 on 2021-01-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BigIntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTagRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BigIntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('course_id', models.BigIntegerField()),
                ('tag_id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTeacherRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BigIntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('course_id', models.BigIntegerField()),
                ('teacher_id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BigIntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('id_card', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=200)),
                ('leader_id', models.BigIntegerField(default=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BigIntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BigIntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BigIntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('id_card', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=200)),
                ('leader_id', models.BigIntegerField(default=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BigIntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('id_card', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=200)),
                ('leader_id', models.BigIntegerField(default=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
