# Generated by Django 3.1.3 on 2020-11-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveBigIntegerField(default=1)),
                ('orgId', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
            ],
            bases=('assistant.basemodel',),
        ),
        migrations.CreateModel(
            name='CourseTagRef',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.basemodel')),
                ('courseId', models.PositiveBigIntegerField()),
                ('tagId', models.PositiveBigIntegerField()),
            ],
            bases=('assistant.basemodel',),
        ),
        migrations.CreateModel(
            name='CourseTeacherRef',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.basemodel')),
                ('courseId', models.PositiveBigIntegerField()),
                ('teacherId', models.PositiveBigIntegerField()),
            ],
            bases=('assistant.basemodel',),
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            bases=('assistant.basemodel',),
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='assistant.basemodel')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('id_card', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=200)),
                ('leaderId', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
            bases=('assistant.basemodel',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.basemodel')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('assistant.basemodel',),
        ),
        migrations.CreateModel(
            name='Emploee',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.people')),
            ],
            bases=('assistant.people',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.people')),
            ],
            bases=('assistant.people',),
        ),
    ]
