# Generated by Django 3.1.3 on 2020-11-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.basemodel'),
        ),
        migrations.AlterField(
            model_name='people',
            name='leaderId',
            field=models.PositiveBigIntegerField(default=-1),
        ),
    ]
