# Generated by Django 3.1.3 on 2020-11-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_auto_20201127_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemodel',
            old_name='orgId',
            new_name='org_id',
        ),
        migrations.RenameField(
            model_name='coursetagref',
            old_name='courseId',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='coursetagref',
            old_name='tagId',
            new_name='tag_id',
        ),
        migrations.RenameField(
            model_name='courseteacherref',
            old_name='courseId',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='courseteacherref',
            old_name='teacherId',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='leaderId',
            new_name='leader_id',
        ),
    ]
