# Generated by Django 3.1 on 2021-01-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_auto_20210113_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('user_id', models.BigIntegerField()),
                ('course_id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coursetagref',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='courseteacherref',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='org',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
