# Generated by Django 3.1 on 2021-01-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_coursetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTimeRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assistant.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CourseTime',
        ),
        migrations.AddField(
            model_name='coursetimeref',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assistant.time'),
        ),
        migrations.AddField(
            model_name='course',
            name='times',
            field=models.ManyToManyField(through='assistant.CourseTimeRef', to='assistant.Time'),
        ),
    ]
