# Generated by Django 3.1 on 2021-01-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_auto_20210124_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='course_id',
            new_name='good_id',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='type',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(null=True, through='assistant.CourseTagRef', to='assistant.Tag'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(null=True, through='assistant.CourseTeacherRef', to='assistant.Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='times',
            field=models.ManyToManyField(null=True, through='assistant.CourseTimeRef', to='assistant.Time'),
        ),
    ]
