# Generated by Django 3.1 on 2021-02-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_auto_20210128_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
