# Generated by Django 3.1 on 2021-02-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_authuserref'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserref',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coursetagref',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='courseteacherref',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coursetimeref',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
