# Generated by Django 3.1 on 2021-02-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_auto_20210208_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='openid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='openid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
