# Generated by Django 3.1 on 2021-02-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0012_auto_20210213_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUserRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=1000, null=True)),
                ('status', models.IntegerField(default=1)),
                ('org_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('course_id', models.BigIntegerField(default=-1)),
                ('user_id', models.BigIntegerField(default=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
