# Generated by Django 3.1 on 2021-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_auto_20210318_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='email',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='org',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
