# Generated by Django 3.1 on 2021-04-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0016_auto_20210404_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserref',
            name='auth_user_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
