# Generated by Django 3.1 on 2021-04-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0018_auto_20210417_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuserref',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courseuserref',
            name='count',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='courseuserref',
            name='price',
            field=models.BigIntegerField(default=-1),
        ),
    ]
