# Generated by Django 3.1 on 2021-04-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0019_auto_20210429_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseuserref',
            old_name='course_id',
            new_name='good_id',
        ),
        migrations.AddField(
            model_name='courseuserref',
            name='type',
            field=models.IntegerField(default=-1),
        ),
    ]
