# Generated by Django 3.1 on 2021-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0020_auto_20210429_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderref',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
